---
title: "gibbs_sampler"
author: "Juan Carlos Martinez-Ovando"
date: "13 de diciembre de 2016"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preámbulo


```{r preambulo}
rm(list = ls())

setwd("C:/JCMO.Trabajo/@Estudiantes/Stefano Molina/Tesis/code/gibbs_sampler/")
path.work <- 'C:/JCMO.Trabajo/@Estudiantes/Stefano Molina/Tesis/code/gibbs_sampler/'
```

## Ejemplo 1: Distribución normal-gamma

```{r ejemplo1, echo=TRUE}
set.seed(1097)
source("gibbs_normalgamma.R")

M <- 10000
thin <- 1000
ejemplo1.out <-gibbs_normalgamma(M=50000,thin=1000)

# Histograma de "x"
hist(ejemplo1.out[,1],M/100)

# Histograma de "x"
hist(ejemplo1.out[,2],M/100)

# Trayectorias de "x"
plot(ejemplo1.out[,1],type='l')

# Trayectorias de "y"
plot(ejemplo1.out[,2],type='l')

# Medias ergódicas de "x"
plot(as.matrix(cumsum(ejemplo1.out[,1]))/as.matrix(c(1:M)))

# Medias ergódicas de "y"
plot(as.matrix(cumsum(ejemplo1.out[,2]))/as.matrix(c(1:M)))

#	Gráficas de diagnóstico
par(mfrow=c(3,2))
	#	Dispersión
	plot(ejemplo1.out,col=1:M)
	#	Trayectorias conjuntas
	plot(ejemplo1.out,type="l")
	#	Trayectorias individuales
	plot(ts(ejemplo1.out[,1]))
	plot(ts(ejemplo1.out[,2]))
	#	Histogramas
	hist(ejemplo1.out[,1],40)
	hist(ejemplo1.out[,2],40)

par(mfrow=c(1,1))  

#	Gráficas de diagnóstico (autocorrelación)
par(mfrow=c(3,2))
	#	Trayectorias individuales
	plot(ts(ejemplo1.out[,1]))
	plot(ts(ejemplo1.out[,2]))
	#	Trayectorias individuales
	acf(ts(ejemplo1.out[,1]))
	acf(ts(ejemplo1.out[,2]))
	# Medias ergódicas de "x"
	plot(as.matrix(cumsum(ejemplo1.out[,1]))/as.matrix(c(1:M)))
	# Medias ergódicas de "y"
	plot(as.matrix(cumsum(ejemplo1.out[,2]))/as.matrix(c(1:M)))
par(mfrow=c(1,1))  
```

## Ejemplo 2: Distribución normal bivariada

```{r ejemplo2, echo=TRUE}
set.seed(1097)
source("gibbs_bigaussian.R")

M <- 10000
rho <- 0
ejemplo2.out <- gibbs_bigaussian(M,rho)

#	Gráficas de diagnóstico
par(mfrow=c(3,2))
	#	Dispersión
	plot(ejemplo2.out,col=1:M)
	#	Trayectorias conjuntas
	plot(ejemplo2.out,type="l")
	#	Trayectorias individuales
	plot(ts(ejemplo2.out[,1]))
	plot(ts(ejemplo2.out[,2]))
	#	Histogramas
	hist(ejemplo2.out[,1],40)
	hist(ejemplo2.out[,2],40)
par(mfrow=c(1,1))  

#	Gráficas de diagnóstico (autocorrelación)
par(mfrow=c(3,2))
	#	Trayectorias individuales
	plot(ts(ejemplo2.out[,1]))
	plot(ts(ejemplo2.out[,2]))
	#	Trayectorias individuales
	acf(ts(ejemplo2.out[,1]))
	acf(ts(ejemplo2.out[,2]))
	#	Histogramas
	hist(ejemplo2.out[,1],40)
	hist(ejemplo2.out[,2],40)
par(mfrow=c(1,1))  
```
